version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/theoziran/caixahabitacao
    steps:
      - checkout
      - run: go get github.com/PuerkitoBio/goquery
      - run: go get github.com/aws/aws-lambda-go/lambda
      - run: GOARCH=amd64 GOOS=linux go build -o main main.go
      - run: zip /tmp/caixa.zip main
      - persist_to_workspace:
          root: /tmp
          paths:
            - caixa.zip
  deploy:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: Install the AWS CLI
          command: |
              python3 -m venv venv
              source venv/bin/activate
              pip install awscli
              aws s3 ls s3://caixa-stack-template || aws s3 mb s3://caixa-stack-template || exit 0
              aws cloudformation package --template cloudformation.yml --s3-bucket caixa-stack-template --output-template-file cloudformation_output.yml
              aws cloudformation deploy --template cloudformation_output.yml --s3-bucket caixa-stack-template --stack-name caixahabitacao-stack --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - "build"
      - "deploy":
          requires:
            - build
          filters:
            branches:
              only: master
