version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/theoziran/caixahabitacao
    steps:
      - checkout
      - run: go get github.com/PuerkitoBio/goquery
      - run: go get github.com/aws/aws-lambda-go/lambda
      - run: go build
